- hosts: ome_server
  become: yes
  gather_facts: yes
  tasks:
    - name: apt updateを実行します
      apt:
        update_cache: yes
    - name: apt safe-upgradeを実行します
      apt:
        upgrade: safe

    - name: aptで各種ツールをインストールします
      ansible.builtin.apt:
        pkg:
          - dstat
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: DockerリポジトリのGPGキーをシステムに追加します
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: DockerリポジトリをAPTソースに追加します
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: yes
    - name: apt install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
    # sudo usermod -aG docker root
    - name: Add remote "{{ ansible_user }}" user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Set TCP/UDP buffers
      ansible.posix.sysctl:
        name: "{{ item.k }}"
        value: "{{ item.v }}"
        state: present
        sysctl_set: true
        reload: true
      loop:
        - { k: "vm.swappiness", v: 5 }
        - { k: "net.core.rmem_default", v: 33554432 }
        - { k: "net.core.rmem_max", v: 33554432 }
        - { k: "net.core.wmem_default", v: 33554432 }
        - { k: "net.core.wmem_max", v: 33554432 }
        - { k: "net.core.somaxconn", v: 33554432 }
        - { k: "net.core.optmem_max", v: 25165824 }
        - { k: "net.core.netdev_max_backlog", v: 33554432 }
        - { k: "net.ipv4.tcp_tw_reuse", v: 1 }
        - { k: "net.ipv4.tcp_fin_timeout", v: 10 }
        - { k: "net.ipv4.tcp_max_syn_backlog", v: 20480 }
        - { k: "net.ipv4.tcp_keepalive_time", v: 10 }
        - { k: "net.ipv4.tcp_keepalive_probes", v: 4 }
        - { k: "net.ipv4.tcp_keepalive_intvl", v: 5 }
        - { k: "net.ipv4.tcp_rfc1337", v: 1 }
        - { k: "net.ipv4.tcp_mem", v: 786432 1048576 26777216 }
        - { k: "net.ipv4.tcp_rmem", v: 8192 87380 33554432 }
        - { k: "net.ipv4.tcp_wmem", v: 8192 65536 33554432 }
        - { k: "net.ipv4.udp_mem", v: 65536 131072 262144 }
        - { k: "net.ipv4.udp_rmem_min", v: 16384 }
        - { k: "net.ipv4.udp_wmem_min", v: 16384 }
        - { k: "fs.file-max", v: 100000 }

    - name: Add or modify limits for wildcard domain
      community.general.pam_limits:
        domain: "{{ item.domain }}"
        limit_type: "{{ item.limit_type }}"
        limit_item: nofile
        value: 65535
      with_items:
        - domain: root
          limit_type: soft
        - domain: root
          limit_type: hard
        - domain: "*"
          limit_type: soft
        - domain: "*"
          limit_type: hard
