version: '3.8'

services:
    sigapp:
        build: .
        container_name: sigapp
        init: true
        restart: always
        tty: true
        env_file: ./.env
        network_mode: "host"
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            #- ./keys/fullchain.pem:/work/keys/fullchain.pem:ro
            #- ./keys/privkey.pem:/work/keys/privkey.pem:ro
        expose:
            - ${APP_PORT:-3000}


