version: '3.8'

services:
    sigapp:
        image: denoland/deno:alpine-1.39.4
        container_name: sigapp
        init: true
        restart: always
        tty: true
        network_mode: "host"
        ports:
            - "3000:3000"
        environment:
            USE_HTTPS: ${USE_HTTPS:-false}
            APP_PORT: ${APP_PORT:-3000}
            OME_SERVER_URL: ${OME_SERVER_URL:-wss://ome-sfu.extreal.net:3334}
            LOGGING: ${LOGGING:-on}
            MESSAGING_CORS_ORIGIN: ${MESSAGING_CORS_ORIGIN:-*}
        working_dir: /src
        volumes:
            - .:/src
            #- ./keys/fullchain.pem:/work/keys/fullchain.pem:ro
            #- ./keys/privkey.pem:/work/keys/privkey.pem:ro
        expose:
            - ${APP_PORT:-3000}
        entrypoint: ["deno", "run", "--allow-env", "--allow-net","--allow-read=/node_modules","./src/index.ts"]

