version: "3.7"

services:
  ome:
    image: airensoft/ovenmediaengine:0.15.3
    container_name: ome_server
    ports:
      - ${OME_ORIGIN_PORT:-9000}:${OME_ORIGIN_PORT:-9000}
      - ${OME_RTMP_PROV_PORT:-1935}:${OME_RTMP_PROV_PORT:-1935}
      - ${OME_SRT_PROV_PORT:-9999}:${OME_SRT_PROV_PORT:-9999}/udp
      - ${OME_SIGNALLING_PORT:-3333}:${OME_SIGNALLING_PORT:-3333}
      - ${OME_SIGNALLING_TLS_PORT:-3334}:${OME_SIGNALLING_TLS_PORT:-3334}
      - ${OME_TCP_RELAY_PORT:-3478}:${OME_TCP_RELAY_PORT:-3478}
      - ${OME_ICE_CANDIDATES_PORT:-10006}:${OME_ICE_CANDIDATES_PORT:-10006}/udp
      - ${OME_API_PORT:-8081}:${OME_API_PORT:-8081}
      - ${OME_API_TLS_PORT:-8082}:${OME_API_TLS_PORT:-8082}
    environment:
      - OME_SERVER_PORT=${OME_SERVER_PORT}
      - OME_RTMP_PROV_PORT=${OME_RTMP_PROV_PORT}
      - OME_SRT_PROV_PORT=${OME_SRT_PROV_PORT}
      - OME_LLHLS_STREAM_PORT=${OME_LLHLS_STREAM_PORT}
      - OME_LLHLS_STREAM_TLS_PORT=${OME_LLHLS_STREAM_TLS_PORT}
      - OME_SIGNALLING_PORT=${OME_SIGNALLING_PORT}
      - OME_SIGNALLING_TLS_PORT=${OME_SIGNALLING_TLS_PORT}
      - OME_TCP_RELAY_ADDRESS=${OME_TCP_RELAY_ADDRESS}
      - OME_ICE_CANDIDATES=${OME_ICE_CANDIDATES}
      - OME_WEBRTC_RTX=${OME_WEBRTC_RTX:-false}
      - OME_WEBRTC_ULPFEC=${OME_WEBRTC_ULPFEC:-false}
      - OME_WEBRTC_JITTER_BUFFER=${OME_WEBRTC_JITTER_BUFFER:-false}
      - OME_API_PORT=${OME_API_PORT}
      - OME_API_TLS_PORT=${OME_API_TLS_PORT}
      - OME_API_ACCESS_TOKEN=${OME_API_ACCESS_TOKEN}
      - OME_DEFAULT_VIRTUALHOST_NAME=${OME_DEFAULT_VIRTUALHOST_NAME}
      - OME_DEFAULT_ORIGIN_SERVER_ADDR=${OME_DEFAULT_ORIGIN_SERVER_ADDR}
    volumes:
      - ${OME_SERVER_CONF}:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m
